import Head from "next/head";
import styles from "../styles/Home.module.css";
import Feeds from "./components/Feeds";
import Menu from "./components/Menu";
import Navbar from "./components/Navbar";
import Widgets from "./components/Widgets";
import { SiGitea } from "react-icons/si";
import { useSelector } from "react-redux";
import { API_URL } from "../helpers";

export default function Home() {
  const { username, fullname, profilepicture } = useSelector(
    (state) => state.user
  );
  return (
    <div className={styles.container}>
      <Head>
        <title>Teatalk</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={"/favicon.ico"} />
      </Head>

      <main className="bg-slate-200 min-h-screen max-w-screen mx-auto">
        <Navbar />
        <div className="flex flex-row min-h-screen">
          <Menu
            username={username}
            fullname={fullname}
            image_url={`${API_URL}${profilepicture}`}
          />
          <Feeds />
          <Widgets />
        </div>
      </main>
    </div>
  );
}
