import React from "react";
import Menu from "./components/Menu";
import Navbar from "./components/Navbar";
import Widgets from "./components/Widgets";
import Profile from "./components/Profile";
import Head from "next/head";
import { useSelector } from "react-redux";

const ProfilePage = () => {
  const { username, fullname } = useSelector((state) => state.user);

  return (
    <div>
      <Head>
        <title>Profile | Teatalk</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={"/favicon.ico"} />
      </Head>

      <main className="bg-slate-200 min-h-screen max-w-screen mx-auto">
        <Navbar />
        <div className="flex flex-row min-h-screen">
          <Menu username={username} fullname={fullname} />
          <Profile username={username} />
          <Widgets />
          {/* Modal */}
        </div>
      </main>
    </div>
  );
};

export default ProfilePage;
